[2017-06-28T00:31:59,769][WARN ][logstash.runner          ] SIGINT received. Shutting down the agent.
[2017-06-28T00:32:00,193][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
[2017-06-28T00:32:05,138][WARN ][logstash.runner          ] Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss.
[2017-06-28T00:32:05,684][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>28, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.15-java/lib/logstash/inputs/beats.rb:196:in `run'"}], ["LogStash::Filters::Mutate", {"rename"=>{"longitude"=>"[location][lon]", "latitude"=>"[location][lat]"}, "remove_field"=>["beat", "message", "tags", "source", "host", "hostname", "@version", "type"], "id"=>"aa52bbd2141100353545f045ed5bae5bfa46e588-3"}]=>[{"thread_id"=>23, "name"=>"[main]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:118:in `synchronize'"}, {"thread_id"=>24, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:118:in `synchronize'"}, {"thread_id"=>25, "name"=>"[main]>worker2", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:136:in `synchronize'"}, {"thread_id"=>26, "name"=>"[main]>worker3", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:118:in `synchronize'"}]}}
[2017-06-28T00:32:05,692][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
